---
abstract: 'A standalone authoring tool for Module::Build::Tiny'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.003, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ModuleBuildTiny
requires:
  Archive::Tar: '0'
  CPAN::Meta: '0'
  Exporter: '5.57'
  File::Path: '0'
  File::Temp: '0'
  Getopt::Long: '2.39'
  JSON::PP: '0'
  Module::CPANfile: '0'
  Module::Metadata: '0'
  perl: '5.008'
version: '0.003'
